### ISSUE TITLE
Add fetching to synopsis

### ISSUE THREAD

**Issue by zoffixznet** [raku-community-modules/Pastebin-Gist#1]

**Comment by 2colours** [comment]
@zoffixznet do you have any clue what you meant by that? :D

**Comment by zoffixznet** [comment]
Just quality of life improvement to docs to add an example for code to fetch contents of an existing paste in the SYNOPSIS section, so someone can just copy paste it.

**Comment by 2colours** [comment]
Thankies <3

**Comment by 2colours** [comment]
Addressed in https://github.com/raku-community-modules/Pastebin-Gist/commit/1abfe4573612529c8679c9fadbc39909d8dd9bfb and https://github.com/raku-community-modules/Pastebin-Gist/commit/8b00bfafa1d58976c814204176b886cfb172b85e
